name: Create or Update the ssm parameters

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  Getting-SSM-Parameters-Ready:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::058264290508:role/Github-Actions-Access
          region: us-east-1

      - name: Update the SSM Parameter
        run: |
          aws sts get-caller-identity
          cd bash-scripts
          bash temp-ssm.sh
      
      - name: Successfully Completed
        run: |
          echo "Successfully executed!!"
